version: '3.3'
services:
  mysql-database:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "todolist"
      MYSQL_DATABASE: "todolist"
    volumes:
      - ./sql/init-todolist.sql:/docker-entrypoint-initdb.d/mysql_schema.sql
    networks:
      local_network:
        ipv4_address: 172.18.0.2

  todo-list:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql-database
    restart: on-failure
    networks:
      local_network:
        ipv4_address: 172.18.0.3

networks:
  local_network:
    ipam:
      config:
        - subnet: 172.18.0.0/16
